// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace GambitGraph.DataAccess
{
    public partial class Gambitbot13Context : DbContext
    {
        public Gambitbot13Context()
        {
        }

        public Gambitbot13Context(DbContextOptions<Gambitbot13Context> options)
            : base(options)
        {
        }

        public virtual DbSet<SpellJobLevels> SpellJobLevels { get; set; }
        public virtual DbSet<Spells> Spells { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SpellJobLevels>(entity =>
            {
                entity.HasKey(e => e.SpellJobLevelId);

                entity.HasOne(d => d.Spell)
                    .WithMany(p => p.SpellJobLevels)
                    .HasForeignKey(d => d.SpellId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_SpellJobLevels_Spells");
            });

            modelBuilder.Entity<Spells>(entity =>
            {
                entity.HasKey(e => e.SpellId)
                    .HasName("PK_SpellsEF");

                entity.Property(e => e.English)
                    .HasColumnName("english")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}