// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GambitGraph.DataAccess
{
    public partial class Nukes
    {
        public int NukeId { get; set; }
        public int SpellId { get; set; }
        public int ActionTypeId { get; set; }
        public int Priority { get; set; }
        public int? NinjaToolId { get; set; }

        public virtual Spells Spell { get; set; }
    }
}