// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GambitGraph.DataAccess
{
    public partial class SpellJobLevels
    {
        public int SpellJobLevelId { get; set; }
        public int SpellId { get; set; }
        public int JobId { get; set; }
        public int RequiredLevel { get; set; }

        public virtual Spells Spell { get; set; }
    }
}