// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GambitGraph.DataAccess
{
    public partial class Spells
    {
        public Spells()
        {
            Absorbs = new HashSet<Absorbs>();
            Heals = new HashSet<Heals>();
            Nukes = new HashSet<Nukes>();
            SpellJobLevels = new HashSet<SpellJobLevels>();
        }

        public int SpellId { get; set; }
        public int Id { get; set; }
        public bool IdSpecified { get; set; }
        public int Index { get; set; }
        public string Prefix { get; set; }
        public string English { get; set; }
        public string Type { get; set; }
        public string Element { get; set; }
        public string Targets { get; set; }
        public string Skill { get; set; }
        public int Mpcost { get; set; }
        public bool MpcostSpecified { get; set; }
        public decimal Casttime { get; set; }
        public bool CasttimeSpecified { get; set; }
        public decimal Recast { get; set; }
        public bool RecastSpecified { get; set; }
        public int Duration { get; set; }
        public string Alias { get; set; }

        public virtual ICollection<Absorbs> Absorbs { get; set; }
        public virtual ICollection<Heals> Heals { get; set; }
        public virtual ICollection<Nukes> Nukes { get; set; }
        public virtual ICollection<SpellJobLevels> SpellJobLevels { get; set; }
    }
}