// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GambitGraph.DataAccess
{
    public partial class Spells
    {
        public Spells()
        {
            SpellJobLevels = new HashSet<SpellJobLevels>();
        }

        public int SpellId { get; set; }
        public string English { get; set; }
        public virtual ICollection<SpellJobLevels> SpellJobLevels { get; set; }
    }
}